version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
    ignore:
      - dependency-name: bincode
        update-types: ["version-update:semver-major"]
    groups:
      oxc:
        patterns: ["oxc_*"]
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
